// Lucide-compatible icon names re-exported from Tabler Icons — mirrors hermes-agent's icon barrel.
// Call sites keep importing familiar names like `FolderOpen`/`SendIcon`; only the underlying icon set changed.
import {
  IconAlertCircle as AlertCircle,
  IconAlertTriangle as AlertTriangle,
  IconArchive as Archive,
  IconArrowDown as ArrowDown,
  IconArrowUp as ArrowUp,
  IconRobot as Bot,
  IconBrain as BrainIcon,
  IconCheck as Check,
  IconCircleCheck as CheckCircle2,
  IconCheck as CheckIcon,
  IconSquareCheck as CheckSquare,
  IconChevronDown as ChevronDown,
  IconChevronDown as ChevronDownIcon,
  IconChevronRight as ChevronRight,
  IconChevronRight as ChevronRightIcon,
  IconChevronUp as ChevronUp,
  IconCircle as Circle,
  IconCopy as Copy,
  IconCpu as Cpu,
  IconDownload as Download,
  IconExternalLink as ExternalLink,
  IconEye as EyeIcon,
  IconEyeOff as EyeOffIcon,
  IconFile as File,
  IconFileCode as FileCode,
  IconFileDownload as FileDown,
  IconJson as FileJson,
  IconFilePlus as FilePlus,
  IconFileText as FileText,
  IconFolder as FolderClosed,
  IconFolder as FolderIcon,
  IconFolderOpen as FolderOpen,
  IconFolderOpen as FolderOpenIcon,
  IconFolderPlus as FolderPlus,
  IconGitBranch as GitBranchIcon,
  IconGitCommit as GitCommitHorizontalIcon,
  IconGitMerge as GitMergeIcon,
  IconGripHorizontal as GripHorizontal,
  IconGripVertical as GripVertical,
  IconHistory as History,
  IconPhoto as Image,
  IconLoader2 as Loader2,
  IconMessageCircle as MessageSquare,
  IconMinus as MinusIcon,
  IconNetwork as Network,
  IconPaperclip as PaperclipIcon,
  IconPencil as Pencil,
  IconPin as Pin,
  IconPlayerPlay as Play,
  IconPlug as Plug,
  IconPlugConnected as PlugZap,
  IconPlus as Plus,
  IconPlus as PlusIcon,
  IconRefresh as RefreshCw,
  IconArrowBackUp as Reply,
  IconRotate2 as RotateCcw,
  IconDeviceFloppy as Save,
  IconSearch as Search,
  IconSearch as SearchIcon,
  IconSend as Send,
  IconSend as SendIcon,
  IconSettings as SettingsIcon,
  IconShield as Shield,
  IconSparkles as Sparkles,
  IconSquare as Square,
  IconTerminal2 as SquareTerminal,
  IconTerminal2 as TerminalIcon,
  IconThumbDown as ThumbsDown,
  IconThumbUp as ThumbsUp,
  IconTrash as Trash2,
  IconTrash as Trash2Icon,
  IconArrowBackUp as Undo2,
  IconUpload as Upload,
  IconWifi as WifiIcon,
  IconWifiOff as WifiOffIcon,
  IconX as X,
  IconCircleX as XCircle,
  IconX as XIcon,
  IconBolt as Zap,
} from '@tabler/icons-react'

export {
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowUp,
  Bot,
  BrainIcon,
  Check,
  CheckCircle2,
  CheckIcon,
  CheckSquare,
  ChevronDown,
  ChevronDownIcon,
  ChevronRight,
  ChevronRightIcon,
  ChevronUp,
  Circle,
  Copy,
  Cpu,
  Download,
  ExternalLink,
  EyeIcon,
  EyeOffIcon,
  File,
  FileCode,
  FileDown,
  FileJson,
  FilePlus,
  FileText,
  FolderClosed,
  FolderIcon,
  FolderOpen,
  FolderOpenIcon,
  FolderPlus,
  GitBranchIcon,
  GitCommitHorizontalIcon,
  GitMergeIcon,
  GripHorizontal,
  GripVertical,
  History,
  Image,
  Loader2,
  MessageSquare,
  MinusIcon,
  Network,
  PaperclipIcon,
  Pencil,
  Pin,
  Play,
  Plug,
  PlugZap,
  Plus,
  PlusIcon,
  RefreshCw,
  Reply,
  RotateCcw,
  Save,
  Search,
  SearchIcon,
  Send,
  SendIcon,
  SettingsIcon,
  Shield,
  Sparkles,
  Square,
  SquareTerminal,
  TerminalIcon,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  Trash2Icon,
  Undo2,
  Upload,
  WifiIcon,
  WifiOffIcon,
  X,
  XCircle,
  XIcon,
  Zap,
}

